### ISSUE TITLE
error : Email Password: Password (again): |--|||||||||||||||||||||| (dockerfile)

### ISSUE THREAD

**Issue by fbclol** [cb109/payshare#7]
hello ,
error  exec python manage.py createsuperuser
FROM python:3-slim-jessie

I need Help me plz ! :(

root@82eab9cc7148:/var/app# python manage.py createsuperuser
Username (leave blank to use 'root'): fbclol
Email address: boue.franck@orange.fr
Password:
Password (again):
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 160, in handle
    validate_password(password2, self.UserModel(**fake_user_data))
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/password_validation.py", line 44, in validate_password
    password_validators = get_default_password_validators()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/password_validation.py", line 19, in get_default_password_validators
    return get_password_validators(settings.AUTH_PASSWORD_VALIDATORS)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/password_validation.py", line 26, in get_password_validators
    klass = import_string(validator['NAME'])
KeyError: 'NAME'

**Comment by cb109** [comment]
I think Django doesn't like this part where I disabled the password validators: https://github.com/cb109/payshare/blob/develop/payshare/settings.py#L109-L122

I don't remember it being a problem, but I guess you can simply remove it from the settings file altogether (as user passwords are not being used at all) and the setup should work. Feel free to reopen if it doesn't.
